batch_size: 16
iters: 120000

train_dataset:
  type: Dataset
  dataset_root: /home/aistudio
  train_path: /home/aistudio/train.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.5
      scale_step_size: 0.25
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: RandomRotation
      max_rotation: 30
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    # - type: RandomPaddingCrop
    #   crop_size: [ 256, 256 ]
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /home/aistudio
  val_path: /home/aistudio/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
  mode: val


model:
  type: DeepLabV3
  num_classes: 2
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  backbone_indices: [3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9
    



loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        #- type: LovaszSoftmaxLoss
        #- type: DiceLoss
      coef: [1.0]
  coef: [1]